####################

- name: test | ping

  hosts: all

  tasks:

    - name: ping

      ping:

####################

- name: test

  become: true

  hosts: all

  roles:

    - role: patch

    - role: ufw

    - role: bounce

    - role: uptime

####################
