####################

- name        : get

  command     : '{{ uptime_command }}'

  changed_when: false

  register    : uptime

####################

- name : display

  debug: msg="{{ inventory_hostname }} has been {{ uptime.stdout }}"

####################
