####################

- name    : patch

  apt     :

    update_cache: yes
    upgrade     : '{{ patch_upgrade_type }}'

  register: patch

####################

- name    : trigger bounce

  when    : patch.changed

  set_fact: bounce_enabled=true

####################
