####################

- name    : reboot

  when    : bounce_enabled

  command : '{{ bounce_reboot_command }}'

  register: bounce

####################

- name        : wait

  when        : bounce.changed

  local_action:

    module: wait_for

    host  : '{{ inventory_hostname }}'
    port  : '{{ bounce_ssh_port    }}'
    delay : '{{ bounce_delay       }}'

####################
